MCHAT_TITLE: str = "chat_title"
MCHAT_ID: str = "chat_id"
MCOMMAND: str = "command"
MUSER_NAME: str = "user_name"
MUSER_TITLE: str = "user_title"
MTEXT: str = "text"
MCAPTION: str = "caption"
MDATE: str = "date"
MCONTENT_TYPE: str = "content_type"
MMESSAGE_ID: str = "message_id"
MUSER_LASTNAME: str = "user_lastname"

SCREENED: str = "\t"
