"""

Revision ID: 365ff0206d59
Revises: ca400c7eaa50
Create Date: 2023-03-16 14:03:57.955010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365ff0206d59'
down_revision = 'ca400c7eaa50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
