"""

Revision ID: 771dd6693ca4
Revises: e93c3ed387a6
Create Date: 2023-03-15 14:29:34.008978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771dd6693ca4'
down_revision = 'e93c3ed387a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_names',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fstatus', sa.INTEGER(), nullable=False),
    sa.Column('fuserid', sa.INTEGER(), nullable=True),
    sa.Column('fusername', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['fuserid'], ['tbl_users.id'], name='fk__tbl_names__fuserid__tbl_users'),
    sa.PrimaryKeyConstraint('id', name='pk__tbl_names'),
    sa.UniqueConstraint('id', name='uq__tbl_names__id')
    )
    # ### end Alembic commands ###
