"""

Revision ID: 793da1c8e64b
Revises: fcea93c1a6b2
Create Date: 2023-03-14 12:56:47.500840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793da1c8e64b'
down_revision = 'fcea93c1a6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
