"""111

Revision ID: bb4c59834853
Revises: 365ff0206d59
Create Date: 2023-03-16 14:06:24.172809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4c59834853'
down_revision = '365ff0206d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_rights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fstatus', sa.Integer(), nullable=False),
    sa.Column('fuserid', sa.Integer(), nullable=True),
    sa.Column('fchatid', sa.Integer(), nullable=True),
    sa.Column('fkarma', sa.Integer(), nullable=True),
    sa.Column('fadmin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fchatid'], ['tbl_chats.id'], name=op.f('fk__tbl_rights__fchatid__tbl_chats')),
    sa.ForeignKeyConstraint(['fuserid'], ['tbl_users.id'], name=op.f('fk__tbl_rights__fuserid__tbl_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tbl_rights')),
    sa.UniqueConstraint('id', name=op.f('uq__tbl_rights__id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_rights')
    # ### end Alembic commands ###
