"""

Revision ID: ca400c7eaa50
Revises: 771dd6693ca4
Create Date: 2023-03-16 12:45:18.348101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca400c7eaa50'
down_revision = '771dd6693ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_penalties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_penalties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fstatus', sa.INTEGER(), nullable=False),
    sa.Column('fuserid', sa.INTEGER(), nullable=True),
    sa.Column('fchatid', sa.INTEGER(), nullable=True),
    sa.Column('ftype', sa.INTEGER(), nullable=True),
    sa.Column('fendsat', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['fchatid'], ['tbl_chats.id'], name='fk__tbl_penalties__fchatid__tbl_chats'),
    sa.ForeignKeyConstraint(['fuserid'], ['tbl_users.id'], name='fk__tbl_penalties__fuserid__tbl_users'),
    sa.PrimaryKeyConstraint('id', name='pk__tbl_penalties'),
    sa.UniqueConstraint('id', name='uq__tbl_penalties__id')
    )
    # ### end Alembic commands ###
