"""

Revision ID: e93c3ed387a6
Revises: 793da1c8e64b
Create Date: 2023-03-15 12:21:04.700320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93c3ed387a6'
down_revision = '793da1c8e64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fusername', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix__tbl_users__fusername'), ['fusername'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__tbl_users__fusername'))
        batch_op.drop_column('fusername')

    # ### end Alembic commands ###
