"""init

Revision ID: ed0e017cb9e1
Revises: 
Create Date: 2022-08-18 16:04:32.011628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0e017cb9e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk__tbl_stat PRIMARY KEY (id), CONSTRAINT uq__tbl_stat__id', 'tbl_stat', type_='unique')
    op.create_unique_constraint(op.f('uq__tbl_stat__id'), 'tbl_stat', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__tbl_stat__id'), 'tbl_stat', type_='unique')
    op.create_unique_constraint('pk__tbl_stat PRIMARY KEY (id), CONSTRAINT uq__tbl_stat__id', 'tbl_stat', ['id'])
    # ### end Alembic commands ###
