"""

Revision ID: fcea93c1a6b2
Revises: 
Create Date: 2023-03-14 12:54:38.855606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcea93c1a6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_stat', schema=None) as batch_op:
        batch_op.drop_constraint('pk__tbl_stat PRIMARY KEY (id), CONSTRAINT uq__tbl_stat__id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq__tbl_stat__id'), ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_stat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq__tbl_stat__id'), type_='unique')
        batch_op.create_unique_constraint('pk__tbl_stat PRIMARY KEY (id), CONSTRAINT uq__tbl_stat__id', ['id'])

    # ### end Alembic commands ###
